name: snakes-site
recipe: lamp
services:
  appserver:
    php: '7.4'
    webroot: ./src
    xdebug: true
  node:
    type: node:16.13

# Add additional tooling
tooling:
  node:
    service: node
  npm:
    service: node

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/lamp": ./../../